//FileOpener.java
//Revision: $Revision: 1.3 $
//Rev Date: $Date: 2007/03/07 07:21:21 $

package dgu.util.swing;

/**
 * Implements by classes which are able to read a file 
 * from a given string.  Used by the recently used menus
 * which may generated by SettingsFile.
 *
 * @author David Underhill
 */
public interface FileOpener {
    
    /** open a file from the specified filename */
    public void openFileFromFN( String fn );
    
}
