/*
 * DemoGUI.java
 *
 * Created on June 5, 2008, 8:47 PM
 */

package dgu.bufsizing;

import dgu.util.swing.GUIHelper;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;

/**
 *
 * @author  dgu
 */
public class DemoGUI extends javax.swing.JFrame {
    public static final java.awt.Image icon = java.awt.Toolkit.getDefaultToolkit().getImage("dgu.gif");
    private static JFreeChart chart;
    
    /** Creates new form DemoGUI */
    public DemoGUI() {
        GUIHelper.setGUIDefaults();
        initComponents();
        setIconImage( icon );
       
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width - 1024) / 2, (screenSize.height - 768) / 2, 1024, 768);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupBound1 = new dgu.util.swing.binding.ButtonGroupBound();
        pnlDetails = new javax.swing.JPanel();
        cboNode = new dgu.util.swing.binding.JComboBoxBound();
        lblBottleneck = new javax.swing.JLabel();
        cboBottleneck = new dgu.util.swing.binding.JComboBoxBound();
        lblNode = new javax.swing.JLabel();
        lblBufferSize = new java.awt.Label();
        slBufferSize = new dgu.util.swing.binding.JSliderBound();
        lblRateLimit = new java.awt.Label();
        slRateLimit = new dgu.util.swing.binding.JSliderBound();
        pnlChart = new ChartPanel(chart);
        pnlSizing = new javax.swing.JPanel();
        optGuido = new dgu.util.swing.binding.JRadioButtonBound();
        optRuleOfThumb = new dgu.util.swing.binding.JRadioButtonBound();
        jSeparator1 = new javax.swing.JSeparator();
        pnlMap = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlDetails.setBorder(null);
        pnlDetails.setLayout(null);

        pnlDetails.add(cboNode);
        cboNode.setBounds(340, 10, 150, 25);

        lblBottleneck.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBottleneck.setText("Bottleneck:");
        pnlDetails.add(lblBottleneck);
        lblBottleneck.setBounds(250, 40, 85, 25);

        pnlDetails.add(cboBottleneck);
        cboBottleneck.setBounds(340, 40, 150, 25);

        lblNode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNode.setText("Node:");
        pnlDetails.add(lblNode);
        lblNode.setBounds(250, 10, 85, 25);

        lblBufferSize.setAlignment(java.awt.Label.CENTER);
        lblBufferSize.setText("Buffer Size = 100ms (*100kb* / 50kb)");
        pnlDetails.add(lblBufferSize);
        lblBufferSize.setBounds(500, 10, 240, 18);

        slBufferSize.setMajorTickSpacing(100);
        slBufferSize.setMaximum(500);
        slBufferSize.setMinorTickSpacing(25);
        slBufferSize.setPaintTicks(true);
        slBufferSize.setValue(100);
        pnlDetails.add(slBufferSize);
        slBufferSize.setBounds(495, 15, 250, 45);

        lblRateLimit.setAlignment(java.awt.Label.CENTER);
        lblRateLimit.setText("Rate Limit = 100Mb/s");
        pnlDetails.add(lblRateLimit);
        lblRateLimit.setBounds(765, 10, 240, 18);

        slRateLimit.setMajorTickSpacing(100);
        slRateLimit.setMaximum(1000);
        slRateLimit.setMinorTickSpacing(50);
        slRateLimit.setPaintTicks(true);
        slRateLimit.setValue(100);
        pnlDetails.add(slRateLimit);
        slRateLimit.setBounds(760, 15, 250, 45);

        pnlChart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlChart.setLayout(null);
        pnlDetails.add(pnlChart);
        pnlChart.setBounds(5, 75, 1015, 440);

        pnlSizing.setBorder(javax.swing.BorderFactory.createTitledBorder("Buffer Sizing Formula"));
        pnlSizing.setLayout(null);

        buttonGroupBound1.add(optGuido);
        optGuido.setText("Flow-Sensitive (Appenzellar '04)");
        pnlSizing.add(optGuido);
        optGuido.setBounds(10, 35, 230, 22);

        buttonGroupBound1.add(optRuleOfThumb);
        optRuleOfThumb.setText("Rule of Thumb");
        optRuleOfThumb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optRuleOfThumbActionPerformed(evt);
            }
        });
        pnlSizing.add(optRuleOfThumb);
        optRuleOfThumb.setBounds(10, 15, 117, 22);

        pnlDetails.add(pnlSizing);
        pnlSizing.setBounds(5, 5, 245, 65);
        pnlDetails.add(jSeparator1);
        jSeparator1.setBounds(0, 0, 1025, 10);

        getContentPane().add(pnlDetails);
        pnlDetails.setBounds(0, 249, 1028, 519);

        pnlMap.setBorder(null);
        pnlMap.setLayout(null);
        getContentPane().add(pnlMap);
        pnlMap.setBounds(0, 0, 1028, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void optRuleOfThumbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optRuleOfThumbActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_optRuleOfThumbActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dgu.util.swing.binding.ButtonGroupBound buttonGroupBound1;
    private dgu.util.swing.binding.JComboBoxBound cboBottleneck;
    private dgu.util.swing.binding.JComboBoxBound cboNode;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBottleneck;
    private java.awt.Label lblBufferSize;
    private javax.swing.JLabel lblNode;
    private java.awt.Label lblRateLimit;
    private dgu.util.swing.binding.JRadioButtonBound optGuido;
    private dgu.util.swing.binding.JRadioButtonBound optRuleOfThumb;
    private org.jfree.chart.ChartPanel pnlChart;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlMap;
    private javax.swing.JPanel pnlSizing;
    private dgu.util.swing.binding.JSliderBound slBufferSize;
    private dgu.util.swing.binding.JSliderBound slRateLimit;
    // End of variables declaration//GEN-END:variables

}
